//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkOut
    {
        public int id { get; set; }
        public string name { get; set; }
        public string destination { get; set; }
        public string package { get; set; }
        public string paymentMethod { get; set; }
        public int Total { get; set; }
        public Nullable<int> check_Id { get; set; }
    
        public virtual register register { get; set; }
    }
}
