//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class register1
    {
        public int id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "Required Field")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Required Field")]

        public string lastName { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Required Field")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Required Field")]
        public int age { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Required Field")]
        public string email { get; set; }
        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Required Field")]
        public int phoneno { get; set; }
        [DisplayName("Address")]
        [Required(ErrorMessage = "Required Field")]
        public string address { get; set; }
        [DisplayName("City")]
        [Required(ErrorMessage = "Required Field")]
        public string city { get; set; }
        [DisplayName("Package Name")]

        public Nullable<int> packages { get; set; }
        [DisplayName("Country you want to go")]
        [Required(ErrorMessage = "Required Field")]
        public string countryTogo { get; set; }
        [DisplayName("Booking Date")]
        [Required(ErrorMessage = "Required Field")]
        public Nullable<System.DateTime> date { get; set; }
        [DisplayName("Payment Method")]
        [Required(ErrorMessage = "Required Field")]
        public string payment { get; set; }

        public virtual package package { get; set; }
    }
}
