//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public register()
        {
            this.checkOuts = new HashSet<checkOut>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public int age { get; set; }
        public string email { get; set; }
        public int phoneno { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string package { get; set; }
        public string countryTogo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string payment { get; set; }
    
        public virtual ICollection<checkOut> checkOuts { get; set; }
    }
}
